import React from 'react';
import { Sparkles, AlertCircle, Info, ShieldAlert } from 'lucide-react';

export const IndustrialInsights = ({ insights }) => {
  if (!insights || insights.length === 0) return null;

  const getSeverityBadge = (severity) => {
    switch (severity) {
      case 'CRITICAL':
        return (
          <span className="inline-flex items-center px-2.5 py-0.5 rounded-md text-[10px] font-bold bg-rose-950 text-rose-300 border border-rose-800 uppercase tracking-widest">
            <ShieldAlert className="w-3 h-3 mr-1 text-rose-400" /> CRITICAL
          </span>
        );
      case 'WARNING':
        return (
          <span className="inline-flex items-center px-2.5 py-0.5 rounded-md text-[10px] font-bold bg-amber-950 text-amber-300 border border-amber-800 uppercase tracking-widest">
            <AlertCircle className="w-3 h-3 mr-1 text-amber-400" /> WARNING
          </span>
        );
      case 'INFO':
      default:
        return (
          <span className="inline-flex items-center px-2.5 py-0.5 rounded-md text-[10px] font-bold bg-cyan-950 text-cyan-300 border border-cyan-800 uppercase tracking-widest">
            <Info className="w-3 h-3 mr-1 text-cyan-400" /> INFO
          </span>
        );
    }
  };

  return (
    <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6 shadow-xl space-y-6">
      <div className="border-b border-slate-800 pb-3 flex justify-between items-center">
        <div>
          <h3 className="text-xs font-bold text-slate-200 uppercase tracking-wider flex items-center">
            <Sparkles className="w-4 h-4 mr-1.5 text-cyan-400" />
            Deterministic Rule-Based Industrial Insights
          </h3>
          <p className="text-[11px] text-slate-400 mt-0.5">
            Automated, reproducible industrial observations generated by evaluating operational metrics against deterministic rule thresholds.
          </p>
        </div>

        <span className="text-xs font-mono text-cyan-400 font-bold bg-slate-950 px-3 py-1 rounded-xl border border-slate-800">
          {insights.length} Insights Active
        </span>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {insights.map((item, idx) => (
          <div key={idx} className="bg-slate-950 p-4 rounded-xl border border-slate-800 space-y-2 flex flex-col justify-between">
            <div className="space-y-1.5">
              <div className="flex items-center justify-between gap-2">
                <span className="text-[10px] font-mono text-slate-400 uppercase tracking-wider">{item.insight_type} INSIGHT</span>
                {getSeverityBadge(item.severity)}
              </div>
              <h4 className="text-sm font-bold text-white font-sans">{item.title}</h4>
              <p className="text-xs text-slate-300 font-sans leading-relaxed">{item.description}</p>
            </div>

            {item.reference_period && (
              <div className="pt-2 border-t border-slate-800/80 flex justify-between items-center text-[10px] font-mono text-slate-500">
                <span>Metric: {item.metric_name || 'N/A'}</span>
                <span>Basis: {item.reference_period}</span>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
};

export default IndustrialInsights;
