"""Report Templates and Disclaimer Constants for Industrial Carbon Intelligence System."""

DISCLAIMER_TEXT = (
    "NOTICE & DISCLAIMER: This document contains model-based estimates and operational insights "
    "generated by the Industrial Carbon Emission Prediction System (Random Forest & XGBoost Ensemble v1.0). "
    "Predictions, scenario simulations, and optimization recommendations are decision-support estimates subject to "
    "model uncertainty and should be validated against actual physical measurements and engineering specifications."
)

EXECUTIVE_SUMMARY_TEMPLATE = (
    "During the reporting period from {period_start} to {period_end}, the facility produced {total_production:,.0f} units "
    "and recorded {total_co2:,.2f} kg of model-predicted CO₂ emissions. The emission intensity was {emission_intensity:.3f} kg CO₂ "
    "per production unit. Compared with historical benchmarks, production-normalized efficiency demonstrates operational stability. "
    "Optimization analysis identified an estimated potential CO₂ reduction of {optimization_reduction:.1f}% under constrained parameters."
)

SYSTEM_METADATA_HEADER = {
    "system_name": "Industrial Carbon Intelligence Platform",
    "version": "v1.0.0",
    "model_ensemble": "Random Forest + XGBoost (v1.0)",
    "confidentiality": "CONFIDENTIAL — FOR INTERNAL USE ONLY",
}
